/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.view;

import client.controler.Client;
import client.model.FriendsRequest;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;
import server.model.UserInfo;
import client.view.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JTextField;


public class MessengerLayout extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form MessengerLayout
     */
    Client c;
    Vector<String> friends;
    DefaultListModel dmRequest;
    Vector<String> request;
    GroupChatGui groupChatname;
    //Vector<String>Chatgroup;
    
    public MessengerLayout(Client c) {
     
        initComponents();
        this.c=c;
        setVisible(true);
        
          //frindsList.setCellRenderer(new RenderList());
       // addContactInList(c.callContactUser());
       // notifyMyFriends();
         addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                System.out.println("Closed");
                MessengerLayout.this.c.terminate();
               // e.getWindow().dispose();
            }
        });
         doYoyAccept();
      //  Chatgroup=new Vector<String>();
    }
    public void appenedRequest(){
      /*  dmRequest=new DefaultListModel();
        dmRequest.clear();
        dmRequest.addElement(new FriendsRequest(friendName, new JButton("accept"),new JButton("refuse") ));
        requestList.setCellRenderer(new RequestList());
        requestList.setModel(dmRequest);*/
        
        request=new Vector<String>();
        request=c.callAddRequest();
        requestList.setListData(request);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        contact = new javax.swing.JLabel();
        container = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        frindsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestList = new javax.swing.JList<>();
        imgPanel = new javax.swing.JPanel();
        stetus = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        groupChat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        messengerMenu = new javax.swing.JMenu();
        signOutMenuItem = new javax.swing.JMenuItem();
        AddContactMenuItem = new javax.swing.JMenuItem();
        CloseMenuItem = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        AboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("contacts");
        setBackground(new java.awt.Color(0, 102, 153));
        setBounds(new java.awt.Rectangle(500, 50, 0, 0));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        contact.setBackground(new java.awt.Color(0, 102, 153));
        contact.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(153, 153, 153));
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("Contacts");

        container.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        frindsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        frindsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        frindsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frindsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(frindsList);

        container.addTab("friends", jScrollPane1);

        requestList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(requestList);

        container.addTab("requests", jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        imgPanel.setBackground(new java.awt.Color(0, 102, 153));

        stetus.setBackground(new java.awt.Color(0, 102, 153));
        stetus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Offline", "busy", "away" }));
        stetus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stetusActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/offline.png"))); // NOI18N

        groupChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/index.png"))); // NOI18N
        groupChat.setToolTipText("group chat");
        groupChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupChatActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-user-icon.png"))); // NOI18N
        jButton1.setToolTipText("add friend");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imgPanelLayout = new javax.swing.GroupLayout(imgPanel);
        imgPanel.setLayout(imgPanelLayout);
        imgPanelLayout.setHorizontalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stetus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imgPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(groupChat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        imgPanelLayout.setVerticalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imgPanelLayout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(stetus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupChat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        messengerMenu.setText("Messenger");
        messengerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messengerMenuActionPerformed(evt);
            }
        });

        signOutMenuItem.setText("Sign out");
        signOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutMenuItemActionPerformed(evt);
            }
        });
        messengerMenu.add(signOutMenuItem);

        AddContactMenuItem.setText("Add Contact");
        AddContactMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddContactMenuItemActionPerformed(evt);
            }
        });
        messengerMenu.add(AddContactMenuItem);

        CloseMenuItem.setText("Close");
        CloseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseMenuItemActionPerformed(evt);
            }
        });
        messengerMenu.add(CloseMenuItem);

        jMenuBar1.add(messengerMenu);

        HelpMenu.setText("Help");

        AboutMenuItem.setText("About");
        AboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuItemActionPerformed(evt);
            }
        });
        HelpMenu.add(AboutMenuItem);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutMenuItemActionPerformed
        new Sign_In(c).setVisible(true);
        c.terminate();
        this.setVisible(false);
        
    }//GEN-LAST:event_signOutMenuItemActionPerformed

    private void AddContactMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddContactMenuItemActionPerformed
            new Add_contact(c).setVisible(true);
    }//GEN-LAST:event_AddContactMenuItemActionPerformed

    private void CloseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseMenuItemActionPerformed

    private void AboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuItemActionPerformed
             JOptionPane.showMessageDialog(this, "chat program \n by: \n donia mohamed \n mohamed ayad \n hadia hany", "Attention", JOptionPane.OK_CANCEL_OPTION);
    }//GEN-LAST:event_AboutMenuItemActionPerformed

    private void messengerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messengerMenuActionPerformed
            
    }//GEN-LAST:event_messengerMenuActionPerformed

    private void frindsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frindsListMouseClicked

         if(evt.getClickCount()==2){
            String selectedFriend=frindsList.getSelectedValue().toString();
            
         //   new ClientGui(c).setVisible(true);
           // c.showClientGui();
           c.showClientGui(selectedFriend,new ClientGui(c));
           
        }
    }//GEN-LAST:event_frindsListMouseClicked

    private void stetusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stetusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stetusActionPerformed

    private void groupChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupChatActionPerformed
       groupChatname= new GroupChatGui(friends,c);
    }//GEN-LAST:event_groupChatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            new Add_contact(c).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void turnOnMData()
    {
        Vector<String> myFriens=c.callContactUser();
        addContactInList(myFriens);
        for(int i=0;i<myFriens.size();i++)
        {
            System.out.println(c.callGetCurrentUserName() + " " + myFriens.get(i));

        }
        notifyMyFriends(myFriens);
    }
    
    
    public Vector<String> getMyFriends()
    {
    
        return friends;
    
    }
    
    
     public void addContactInList(Vector<String> vec){
       friends=vec;  
       //frindsList.setCellRenderer(new RenderList());
       frindsList.setListData(vec);
       updateOnlineStatue(vec);
       Thread startUpdatingStatue=new Thread(this);
       startUpdatingStatue.start();
       
     }
   
    public void updateOnlineStatue(Vector<String> vec){
          Vector<String> onlineFriends=c.callCheckOnline(vec);
         for(int i=0;i<onlineFriends.size();i++)
            System.out.println(c.callGetCurrentUserName()+ " has:" + onlineFriends.get(i) +" is online now");
  
     }


     public void updateMyContacts(){
         addContactInList(c.callContactUser());
     
     }
     
     public void notifyMyFriends(Vector<String> myFriend){
         c.sendNotifyToFriends(myFriend);

     }
     
     
     @Override
    public void run() {
        
        while(true){
            try {
                Thread.sleep(30000);
                updateOnlineStatue(friends);
               // updateMyContacts();
                
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        
        
        
        }
    }
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessengerLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessengerLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessengerLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessengerLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessengerLayout().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JMenuItem AddContactMenuItem;
    private javax.swing.JMenuItem CloseMenuItem;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JLabel contact;
    private javax.swing.JTabbedPane container;
    private javax.swing.JList<String> frindsList;
    private javax.swing.JButton groupChat;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu messengerMenu;
    private javax.swing.JList<String> requestList;
    private javax.swing.JMenuItem signOutMenuItem;
    private javax.swing.JComboBox stetus;
    // End of variables declaration//GEN-END:variables
    
            
            
    void reciveRequest(String friendUsername) {
        
        int num =JOptionPane.showConfirmDialog(this,"you recived a request from"+friendUsername+"you want to accept this friend??!!","request friend",JOptionPane.YES_NO_OPTION);
        if(num==0){
                    boolean res=c.callHasAcc(friendUsername);

                if(!res){
                     JOptionPane.showMessageDialog(this,"cannot add this user as friend","warning",JOptionPane.WARNING_MESSAGE,null);
                    // friendUsername.setText("");
                }
                else{
                    int currentUserId=c.callCheckAmbigFriend(friendUsername);
                        if(currentUserId!=0){
                            c.callAddFriend(currentUserId,friendUsername);
                            this.setVisible(false);

                        }
                        else{
                            JOptionPane.showMessageDialog(this,"friend name already exist","warning",JOptionPane.WARNING_MESSAGE,null);
                        }

                }
    }
    
}
    public void doYoyAccept() {
        appenedRequest();
        System.out.println("appendRequest");
       /* int num=  JOptionPane.showConfirmDialog(this,"you recived a Friend Request From '"+fromCurrentUser+"'  do you want to accept it ??!","Friend Request",JOptionPane.YES_NO_OPTION);
        
            if(num==0){
                    boolean res=c.callHasAcc(fromCurrentUser);

                if(!res){
                     JOptionPane.showMessageDialog(this,"cannot add this user as friend","warning",JOptionPane.WARNING_MESSAGE,null);
                    // friendUsername.setText("");
                }
                else{
                    int currentUserId=c.callCheckAmbigFriend(fromCurrentUser);
                        if(currentUserId!=0){
                            c.callAddFriend(currentUserId,fromCurrentUser);
                            this.setVisible(false);

                        }
                        else{
                            JOptionPane.showMessageDialog(this,"friend name already exist","warning",JOptionPane.WARNING_MESSAGE,null);
                        }

                }
                setVisible(true);
    }*/
        
        
        
        }
    
    
  /*  public Vector<String> getVecOfChatGroup(){
        
        Chatgroup=groupChatname.getVecName();
        return Chatgroup;   
    }*/
}